import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="w-screen h-screen bg-muted/100">
        <div className="w-full h-[6vh]">
          <Navbar />
        </div>
        <div className="w-full h-[94vh]">
          {children}
        </div>
      </body>
    </html>
  );
}
